services:
  postgres:
    container_name: postgres
    image: postgres:12
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/vat/lib/postgresql/data
  superfrete-api:
    container_name: superfrete-api
    image: superfrete-api
    build: .
    command: sh -c "sleep 10 && ./main"
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - postgres

volumes:
  pgdata: {}
